Create endpoint to upload peer list
iron-fish/ironfish-api pull request #940
Opened 2022-06-29 00:31 UTC by danield9tqh

## Summary
Create an endpoint in telemetry for nodes to upload peer lists. This will be used to create a network topology graph

## Testing Plan

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
```

2022-06-29 17:02 UTC, rohanjadvani requested changes
I think it'd be good to chunk out this PR into several smaller changes:
* Migration for new table
* Service to create/upsert records
* Controller to accept requests

What do you think?

2022-06-29 17:02 UTC, rohanjadvani commented on src/telemetry/telemetry.controller.ts
> +    await Promise.all(promises);
We shouldn't use a `Promise.all` on these payloads since that can lead to starvation for the DB.

2022-06-29 17:02 UTC, rohanjadvani commented on src/telemetry/dto/write-peer-list.dto.ts
> +  readonly nodeId!: string;
We use snake case for our API payloads

```suggestion
  readonly node_id!: string;
```

2022-06-29 23:01 UTC, danield9tqh commented on src/telemetry/telemetry.controller.ts
> +          uq_peer_connection_on_source_dest_time: upload,
No, not intentionally. I did want to keep them unique on these 3 fields. If that's the case is there a better option than `upsert` here?

2022-07-05 03:16 UTC, closed without merging

2022-07-05 03:17 UTC, danield9tqh commented
closing this because we decided to use telemetry / influxdb to upload the peer list instead